### ISSUE TITLE
Suggerimento

### ISSUE THREAD

**Issue by Dario407** [intersecato/PedroPack#1]
Ciao sono un'utente di tecnocraft.
Ti suggerirei di far approvare la tua resource pack nella [_sezione sul forum_](https://forum.tecnocraft.net/forums/proposte-resource-pack/)_ cosi potrebbe essere utilizabile dalla comunity.
Inoltre ti consiglierei anche di magari mostrare delle immagini su cosa cambia.

**Comment by Dario407** [comment]
Aggiungerei anche che il tuo logo ogni tanto è leggermente spammato,tipo sull'aereo

**Comment by intersecato** [comment]
La pack è già in attesa di approvazione da parte dello Staff. Gli utenti verranno notificati di conseguenza al termine della procedura.

**Comment by intersecato** [comment]
Pack **approvata**.
